# Generated by Django 5.1.6 on 2025-02-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_description_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
